server:
  port: 8888
spring:
  application:
    name: system-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bohr-fu/cloud-config/
          search-paths: repo
          username:
          password:
          basedir: config-repo/my-cloud
      label: master


